name: Docker Build & Push

on:
  push:
    paths-ignore:
      - "**.md"
      - "**/.gitignore"
  pull_request:
  workflow_dispatch:

jobs:
  restic:
    uses: thesilkky/workflows/.github/workflows/docker-build-push.yml@main
    with:
      image: thesilkky/restic
      image-version: '0.16.0'
      context: .
      build-args: RESTIC_VERSION=0.16.0
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
